### ISSUE TITLE
Reboot/crash with video that has chapters when trying to bring up OSD controls

### ISSUE THREAD

**Issue by docthomas** [Pivosgroup/buildroot-linux#11]
I have recently noticed that when I try to pause or stop that has chapters and the video is in the last chapter XBMC will crash and restart.  I have tried grabing a snipit from some of the videos that I have seen this with but they don't seem to have the same issue in the smaller form.  

Here is one of the outputs

General
Unique ID                                : 184524911228956073705188749326603466997 (0x8AD23488205CF095832B12E545CF38F5)
Complete name                            : H:\ServerFolders\Videos\TV\The Wire\Season 1\The Wire s01e01.mkv
Format                                   : Matroska
Format version                           : Version 1
File size                                : 892 MiB
Duration                                 : 1h 2mn
Overall bit rate                         : 2 006 Kbps
Movie name                               : The Wire - Season 1, Episode 1
Encoded date                             : UTC 2008-02-24 09:50:16
Writing application                      : mkvmerge v2.0.2 ('You're My Flame') built on Feb 21 2007 23:40:55
Writing library                          : libebml v0.7.7 + libmatroska v0.8.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 9 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1h 2mn
Bit rate                                 : 1 426 Kbps
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.194
Stream size                              : 618 MiB (69%)
Title                                    : x264 L4.1 1426kbps
Writing library                          : x264 core 57 svn-709C
Encoding settings                        : cabac=1 / ref=6 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / fpel_cmp=sad / subme=5 / me-prepass=0 / brdo=0 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / chroma_qp_offset=0 / threads=3 / nr=0 / decimate=1 / mbaff=0 / bframes=3 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=3 / wpredb=1 / bime=1 / keyint=250 / keyint_min=25 / scenecut=40(pre) / rc=2pass / bitrate=1426 / ratetol=1.0 / rceq='blurCplx^(1-qComp)' / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / pb_ratio=1.30
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 2mn
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 171 MiB (19%)
Title                                    : Movie AC3 5.1 384kbps
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Format profile                           : Dolby Digital
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 2mn
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 85.3 MiB (10%)
Title                                    : Commentary AC3 2.0 192kbps
Language                                 : English
Default                                  : No
Forced                                   : No

Text
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Movie SRT
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 1
00:12:03.932                             : en:Chapter 2
00:20:36.032                             : en:Chapter 3
00:30:22.432                             : en:Chapter 4
00:36:39.765                             : en:Chapter 5
00:50:27.199                             : en:Chapter 6

**Comment by davilla** [comment]
which xbmc version ?

**Comment by docthomas** [comment]
Running the last Linux Beta release that was posted publicly.  If you need the git number from XBMC binary let me know how I can get it from SSH and I will send that to you. 

Firmware Release:
Date: 10/09/12
