### ISSUE TITLE
Wrong Movie Runtimes in mkv

### ISSUE THREAD

**Issue by ghost** [Pivosgroup/buildroot-linux#12]
The slider bar reports the wrong runtime for all my mkv files. Others report the same, see:

http://www.pivosforums.com/viewtopic.php?f=25&t=1087

**Comment by davilla** [comment]
More info,  everything that is ripped using MakeMKV (latest versions both linux and windows) shows up with the wrong run time under the latest Xios linux version (don't know about android any more). However the "official" linux release (11.0 compiled mar 24 2012) reads the runtime correctly.

**Comment by ghost** [comment]
Where is the 'official' linux release image? That would be good for testing and comparison, but I can't find it anywhere. Do you have to check out an old version and build it? This may be more than I have time to do..

**Comment by davilla** [comment]
not a clue, the user did not provide enough info :)

**Comment by ghost** [comment]
Wha? shouldn't pivos provide the 'official' linux releases? Why does the user have to provide that?

Or is "official" not really official?

**Comment by davilla** [comment]
11.0 compiled mar 24 2012 does not give me enough info to track it down.

**Comment by davilla** [comment]
could be they mean XBMC mainline desktop...

**Comment by ghost** [comment]
Ah - I see what you're saying. To me a build on different hardware isn't as interesting a comparison point. I just assumed it would be previous releases on xios. So useful as a comparison, but you can't go looking at code differences as easily.

I will try a non-mkv file when I get a chance, as that's all I've done is mkv, just to verify it's container specific.

**Comment by ghost** [comment]
I think this is working now with 121512 M1 build. Haven't looked for exact details, but it seems to be closer.
