### ISSUE TITLE
DTS volume drop

### ISSUE THREAD

**Issue by speedst3r** [Pivosgroup/buildroot-linux#13]
Any file I play with a 1500kbps DTS track experiences a drop in volume every few seconds (between 3 and 10). The receiver maintains an audio lock but the audio drops in volume briefly (less than 0.5s), enough to be noticeable. This is only on the unit that has passthrough enabled to a Pioneer VSX-1019AH. I have a second unit that has no passthrough options selected at all (to a TV) and it does not have this issue.

Issue occurs when playing video file from network or USB connected hard disk.

I did not see this issue on one of my previous git builds (Frodo alpha 7).

I could provide a sample but it happens on every DTS track I have tried - about a dozen files.

**Comment by yang299kms** [comment]
I have the same problem, playing content with 1500k dts audio

**Comment by davilla** [comment]
Please provide the buildroot-linux git hash of your test case. Git is going to churn fast and furious soon.

**Comment by speedst3r** [comment]
c5277fb

**Comment by speedst3r** [comment]
Seems like it could be resolved in 2e8a464 .

Tested two videos with DTS and no volume drop/clipping.
