### ISSUE TITLE
Output of 755 DTS Tracks - passthrough fails

### ISSUE THREAD

**Issue by cscd98** [Pivosgroup/buildroot-linux#16]

**Comment by ghost** [comment]
I fail to get passthrough on DTS to my denon avr-1712, verified with 2 movies. Both are 754kbps according to mediainfo (what mediainfo is rounding down..).

They downmix to stereo fine if I say the dvr is not dts capable (it is though)

This is with mkv files served over nfs.

**Comment by davilla** [comment]
version ?

**Comment by ghost** [comment]
sorry - linux 100912

**Comment by ghost** [comment]
Fixed in 121512 M1 release for me now.
