### ISSUE TITLE
mkv vobsub subtitles not working

### ISSUE THREAD

**Issue by ghost** [Pivosgroup/buildroot-linux#17]
Subititles don't appear. I verified they're in the mkv's with mediainfo, and work fine on an android tablet using mx player pro.

version 100912

**Comment by davilla** [comment]
still a problem ?

**Comment by ghost** [comment]
It is as of xbmc-linux-m1 010813

It's maybe better or I've just figured out a weird little workaround - they don't appear when you turn them on for video. 

But, if while viewing the movie you bring up the OSD, then "cancel", you can usually get them to appear and stick around. It sometimes takes a couple attempts.  If you bring up the OSD again they might disappear. So fiddling with it you can get them to appear. Sometimes they show up with what looks like 50% transparency, sometimes solid.

So broken, but somehow intertwined with the OSD.

**Comment by davilla** [comment]
this was fixed post xbmc-linux-m1 010813

**Comment by ghost** [comment]
Ok, then close it. I'll make a new issue if I got to a new version and it has the same problem.
