### ISSUE TITLE
Pause not really working

### ISSUE THREAD

**Issue by yang299kms** [Pivosgroup/buildroot-linux#18]
commit 2e8a4644e9

with this commit (2e8a4644e9) doesn't really pause, it slows the video down and it does ~1 frame per second skipping some frames.

**Comment by davilla** [comment]
Need to be much more detailed, are you pausing some streaming addon, are you pausing some video over shared content, are you pausing video over local content. Is this for all video content in any container or some specific container.

**Comment by yang299kms** [comment]
This is content via nas shares and content via mythtv pvr plugin. Only have mkv via Nfs shares. 1080/720 bpth

**Comment by davilla** [comment]
fixed in https://github.com/Pivosgroup/xbmc/commit/705db963e6baf9464275304370e0c3bd80a3b313
not yet synced to buildroot-linux.
