### ISSUE TITLE
rmvb no longer works

### ISSUE THREAD

**Issue by yang299kms** [Pivosgroup/buildroot-linux#20]
Plaing rmvb from network or local sd card results in the following (this is since the dvd codec change), worked on all previous builds. Built with d1d9af3f4c.

20:27:38 T:1169519712   DEBUG: CNFSFile::Open - opened volume1/Misc/NGEW TVB/SSSS-31-TVBN.rmvb  
20:27:38 T:1169519712   DEBUG: ScanForExternalSubtitles: Searching for subtitles...  
20:27:38 T:1169519712   DEBUG: ScanForExternalSubtitles: END (total time: 81 ms)  
20:27:38 T:1169519712  NOTICE: Creating Demuxer  
20:27:38 T:1169519712   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/players/dvdplayer/avcodec-53-arm.so)  
20:27:38 T:1169519712   DEBUG: Loading: /usr/lib/xbmc/system/players/dvdplayer/avcodec-53-arm.so  
20:27:38 T:1093865120   DEBUG: ------ Window Init (DialogBusy.xml) ------  
20:27:38 T:1093865120   DEBUG: Window DialogBusy.xml was already loaded  
20:27:38 T:1093865120   DEBUG: Alloc resources: 0.02m  
20:27:38 T:1169519712   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/players/dvdplayer/avformat-53-arm.so)  
20:27:38 T:1169519712   DEBUG: Loading: /usr/lib/xbmc/system/players/dvdplayer/avformat-53-arm.so  
20:27:39 T:1169519712   DEBUG: Open - probing detected format [rm]  
20:27:39 T:1169519712   DEBUG: Open - avformat_find_stream_info starting  
20:27:40 T:1169519712   DEBUG: Open - av_find_stream_info finished  
20:27:40 T:1169519712  NOTICE: Opening video stream: 1 source: 256  
20:27:40 T:1169519712  NOTICE: Creating video codec with codec id: 71  
20:27:40 T:1169519712   DEBUG: CDVDFactoryCodec: compiled in hardware support: CrystalHD:no AMCodec:yes OpenMax:no VDPAU:no VAAPI:no
20:27:40 T:1169519712    INFO: Amlogic Video Decoder...  
20:27:40 T:1169519712   DEBUG: FactoryCodec - Video:  - Opening  
20:27:40 T:1169519712   DEBUG: SECTION:LoadDLL(libamplayer.so)  
20:27:40 T:1169519712   DEBUG: Loading: libamplayer.so  
20:27:40 T:1169519712    INFO: DVDVideoCodecAmlogic: Opened Amlogic Codec  
20:27:40 T:1169519712   DEBUG: FactoryCodec - Video: am-rv - Opened  
20:27:40 T:1169519712  NOTICE: Creating video thread  
20:27:40 T:1284289632  NOTICE: Thread CDVDPlayerVideo start, auto delete: false  
20:27:40 T:1284289632  NOTICE: running thread: video_thread  
20:27:40 T:1169519712  NOTICE: Opening audio stream: 0 source: 256  
20:27:40 T:1284289632   DEBUG: CDVDPlayerVideo - CDVDMsg::GENERAL_SYNCHRONIZE  
20:27:40 T:1169519712  NOTICE: Finding audio codec for: 86018  
20:27:40 T:1169519712   DEBUG: FactoryCodec - Audio: passthrough - Opening  
20:27:40 T:1169519712   DEBUG: FactoryCodec - Audio: passthrough - Failed  
20:27:40 T:1169519712   DEBUG: FactoryCodec - Audio: FFmpeg - Opening  
20:27:40 T:1169519712   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/players/dvdplayer/swresample-0-arm.so)  
20:27:40 T:1169519712   DEBUG: Loading: /usr/lib/xbmc/system/players/dvdplayer/swresample-0-arm.so  
20:27:40 T:1169519712   DEBUG: FactoryCodec - Audio: FFmpeg - Opened  
20:27:40 T:1169519712  NOTICE: Creating audio thread  
20:27:40 T:1275901024  NOTICE: Thread CDVDPlayerAudio start, auto delete: false  
20:27:40 T:1275901024  NOTICE: running thread: CDVDPlayerAudio::Process()  
20:27:40 T:1169519712   DEBUG: CDVDPlayer::SetCaching - caching state 3  
20:27:40 T:1275901024  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)  
20:27:40 T:1275901024    INFO: CSoftAE::MakeStream - AE_FMT_S16NE, 44100, FL,FR  
20:27:40 T:1284289632    INFO: CDVDPlayerVideo - Stillframe left, switching to normal playback  
20:27:40 T:1284289632   DEBUG: CAmlogic::OpenDecoder  
20:27:40 T:1284289632   DEBUG: codecid_to_vformat, format(4), id(71)  
20:27:40 T:1102410848   DEBUG: CSoftAE::Run - Sink restart flagged  
20:27:40 T:1102410848    INFO: CSoftAE::InternalOpenSink - keeping old sink with : AE_FMT_FLOAT, FL,FR, 44100hz  
20:27:40 T:1102410848   DEBUG: CSoftAE::InternalOpenSink - Using speaker layout: 2.0  
20:27:40 T:1102410848   DEBUG: CSoftAE::InternalOpenSink - Internal Buffer Size: 4096  
20:27:40 T:1102410848   DEBUG: AERemap: Downmix normalization is disabled  
20:27:40 T:1102410848   DEBUG: CSoftAEStream::CSoftAEStream - Converting from AE_FMT_S16NE to AE_FMT_FLOAT  
20:27:40 T:1275901024   DEBUG: CDVDPlayerAudio:: synctype set to 0: clock feedback  
20:27:40 T:1169519712   DEBUG: CDVDPlayer::CheckContinuity - wrapback :2, prev:167000.000000, curr:120000.000000, diff:-47000.000000
20:27:40 T:1169519712   DEBUG: CDVDPlayer::HandleMessages - player started 1  
20:27:40 T:1284289632   DEBUG: codec_tag_to_vdec_type, dec_type(0), codec_tag(808736338)  
20:27:40 T:1284289632   DEBUG: CAmlogic::OpenDecoder hints.fpsrate(25), hints.fpsscale(1), video_rate(3840)  
20:27:40 T:1284289632   DEBUG: CAmlogic::OpenDecoder hints.aspect(0.000000), video_ratio.num(1), video_ratio.den(1)  
20:27:40 T:1284289632   DEBUG: CAmlogic::OpenDecoder hints.orientation(0), hints.forced_aspect(1)  
20:27:40 T:1284289632   DEBUG: CAmlogic::OpenDecoder codec init failed, ret=-0x1000005  
20:27:40 T:1284289632   ERROR: DVDVideoCodecAmlogic: Failed to open Amlogic Codec

**Comment by yang299kms** [comment]
local file has slightly shorter error:

20:37:40 T:1169519712   DEBUG: ReadEditDecisionLists - Checking for edit decision lists (EDL) on local drive or remote share for: /media/usb0/TC-22-TVBN.rmvb  
20:37:40 T:1203164256  NOTICE: running thread: CDVDPlayerAudio::Process()  
20:37:40 T:1169519712   DEBUG: CDVDPlayer::SetCaching - caching state 3  
20:37:40 T:1203164256  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
20:37:40 T:1203164256    INFO: CSoftAE::MakeStream - AE_FMT_S16NE, 44100, FL,FR  
20:37:40 T:1288295520    INFO: CDVDPlayerVideo - Stillframe left, switching to normal playback  
20:37:40 T:1288295520   DEBUG: CAmlogic::OpenDecoder  
20:37:40 T:1102410848   DEBUG: CSoftAE::Run - Sink restart flagged  
20:37:40 T:1102410848    INFO: CSoftAE::InternalOpenSink - keeping old sink with : AE_FMT_FLOAT, FL,FR, 44100hz  
20:37:40 T:1102410848   DEBUG: CSoftAE::InternalOpenSink - Using speaker layout: 2.0  
20:37:40 T:1102410848   DEBUG: CSoftAE::InternalOpenSink - Internal Buffer Size: 4096  
20:37:40 T:1288295520   DEBUG: codecid_to_vformat, format(4), id(71)  
20:37:40 T:1288295520   DEBUG: codec_tag_to_vdec_type, dec_type(0), codec_tag(808736338)  
20:37:40 T:1288295520   DEBUG: CAmlogic::OpenDecoder hints.fpsrate(25), hints.fpsscale(1), video_rate(3840)  
20:37:40 T:1288295520   DEBUG: CAmlogic::OpenDecoder hints.aspect(0.000000), video_ratio.num(1), video_ratio.den(1)  
20:37:40 T:1288295520   DEBUG: CAmlogic::OpenDecoder hints.orientation(0), hints.forced_aspect(1)  
20:37:40 T:1288295520   DEBUG: CAmlogic::OpenDecoder codec init failed, ret=-0x1000005  
20:37:40 T:1288295520   ERROR: DVDVideoCodecAmlogic: Failed to open Amlogic Codec  
20:37:40 T:1102410848   DEBUG: AERemap: Downmix normalization is disabled  
20:37:40 T:1102410848   DEBUG: CSoftAEStream::CSoftAEStream - Converting from AE_FMT_S16NE to AE_FMT_FLOAT  
20:37:40 T:1203164256   DEBUG: CDVDPlayerAudio:: synctype set to 0: clock feedback  
20:37:40 T:1169519712   DEBUG: CDVDPlayer::HandleMessages - player started 1  
20:37:40 T:1169519712   DEBUG: CDVDPlayer::CheckContinuity - wrapback :2, prev:167000.000000, curr:120000.000000, diff:-47000.000000

**Comment by yang299kms** [comment]
here is the video link
https://dl.dropbox.com/u/76471871/TC-22-TVBN.rmvb

**Comment by davilla** [comment]
fixed in https://github.com/Pivosgroup/buildroot-linux/commit/48ae4326cd54c1ce46cb80a91e156b685a026b06
