### ISSUE TITLE
VC-1 encoded files made from bluray with Makemkv do not playback correctly.

### ISSUE THREAD

**Issue by extension23** [Pivosgroup/buildroot-linux#22]
VC-1 encoded files still do not work for me. These have not worked on any of the previous releases and still do not work on the latest pull from buildroot-linux. 

 All of my VC-1 files were created with MakeMKV as direct rips from the original bluray.  Here is snippet from the media info example of one that fails. I get audio but for video I get a green garbled screen.   If someone can tell me how to cut down a VC-1 encoded file to make a sample I will provide a sample as well.

Format : Matroska
Format version : Version 2
File size : 19.2 GiB
Duration : 2h 28mn
Overall bit rate : 18.5 Mbps
Encoded date : UTC 2011-03-18 23:38:43
Writing application : MakeMKV v1.6.5 win(x86-release)
Writing library : libmakemkv v1.6.5 (0.7.7/0.8.1) win(x86-release)

Video
ID : 1
Format : VC-1
Format profile : Advanced@L3
Codec ID : WVC1
Codec ID/Hint : Microsoft
Duration : 2h 28mn
Bit rate : 13.0 Mbps
Width : 1 920 pixels
Height : 1 080 pixels
Display aspect ratio : 16:9
Frame rate : 23.976 fps
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Compression mode : Lossy
Bits/(Pixel*Frame) : 0.262
Stream size : 13.5 GiB (71%)
Language : English
Default : Yes
Forced : No

**Comment by davilla** [comment]
use dd and cut 50-100MBs from the beginning.

**Comment by extension23** [comment]
Davilla,

Here is link to a zip file with clips from 3 movies.  I tested them and they work just fine in both openelec (2.9.5) and on Eden under windows, but they do not play correctly on any of the pivos builds.  Let me know if you need more info on the original files.

https://www.dropbox.com/s/zveuc1yzo2cp20k/clips.zip

**Comment by davilla** [comment]
thanks, reproduced and am looking closer.

**Comment by davilla** [comment]
should be fixed
