### ISSUE TITLE
Pause issue 

### ISSUE THREAD

**Issue by yang299kms** [Pivosgroup/buildroot-linux#24]
if i pause for a long period of time, say 2mins. when i unease the video is frozen w/ a couple of frames changing and no audio. I have to stop the video and resume playing.
## these messages would keep repeating

11:30:25 T:1357554784   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
11:30:25 T:1357554784   ERROR: AddPackets - failed to add leftover bytes to render
## 11:30:25 T:1357554784   DEBUG: CDVDPlayerAudio:: Discontinuity - was:2597430167.000000, should be:2595584000.000000, error:-1846167.000000

my log:

11:29:08 T:1093865120   DEBUG: Keyboard: scancode: 19, sym: 0070, unicode: 0070, modifier: 0
11:29:08 T:1093865120   DEBUG: OnKey: p (f050) pressed, action is Play
11:29:08 T:1093865120   DEBUG: CAnnouncementManager - Announcement: OnPause from xbmc
11:29:08 T:1093865120   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPause
11:29:08 T:1093865120   DEBUG: ------ Window Init (DialogSeekBar.xml) ------
11:29:08 T:1093865120   DEBUG: Window DialogSeekBar.xml was already loaded
11:29:08 T:1093865120   DEBUG: Alloc resources: 8.35m
11:29:08 T:1102410848   DEBUG: CSoftAE::Run - Sink restart flagged
11:29:08 T:1102410848    INFO: CSoftAE::InternalOpenSink - RAW passthrough enabled
11:29:08 T:1102410848    INFO: CSoftAE::InternalOpenSink - keeping old sink with : AE_FMT_AC3, FL,FR, 48000hz
11:29:08 T:1102410848   DEBUG: CSoftAE::InternalOpenSink - Internal Buffer Size: 2048

11:30:18 T:1093865120   DEBUG: Keyboard: scancode: 19, sym: 0070, unicode: 0070, modifier: 0
11:30:18 T:1093865120   DEBUG: OnKey: p (f050) pressed, action is Play
11:30:18 T:1102410848   DEBUG: CSoftAE::Run - Sink restart flagged
11:30:18 T:1102410848    INFO: CSoftAE::InternalOpenSink - RAW passthrough enabled
11:30:18 T:1102410848    INFO: CSoftAE::InternalOpenSink - keeping old sink with : AE_FMT_AC3, FL,FR, 48000hz
11:30:18 T:1102410848   DEBUG: CSoftAE::InternalOpenSink - Internal Buffer Size: 2048
11:30:18 T:1357554784   DEBUG: CDVDPlayerAudio:: Discontinuity - was:2594423312.616402, should be:2594632125.166666, error:208812.550264
11:30:18 T:1093865120   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
11:30:18 T:1093865120   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
11:30:18 T:1093865120   DEBUG: ------ Window Deinit (DialogSeekBar.xml) ------
11:30:20 T:1357554784   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
11:30:20 T:1357554784   DEBUG: CDVDPlayerAudio:: Discontinuity - was:2596523490.166666, should be:2595488000.000000, error:-1035490.166666
11:30:21 T:1357554784   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
11:30:21 T:1357554784   ERROR: AddPackets - failed to add leftover bytes to render
11:30:21 T:1357554784   DEBUG: CDVDPlayerAudio:: Discontinuity - was:2597383525.000000, should be:2595520000.000000, error:-1863525.000000
11:30:23 T:1186296928 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
11:30:23 T:1357554784   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
11:30:23 T:1357554784   DEBUG: CDVDPlayerAudio:: Discontinuity - was:2597430069.000000, should be:2595520000.000000, error:-1910069.000000
11:30:23 T:1186296928    INFO: CDVDPlayerVideo - Stillframe detected, switching to forced 23.976024 fps
11:30:25 T:1357554784   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
11:30:25 T:1357554784   ERROR: AddPackets - failed to add leftover bytes to render
11:30:25 T:1357554784   DEBUG: CDVDPlayerAudio:: Discontinuity - was:2597430167.000000, should be:2595584000.000000, error:-1846167.000000
^C
[root@buildroot /root]#

**Comment by davilla** [comment]
if you look further back in the log, does SoftAE audio suspend the audio sink after pausing ?

**Comment by davilla** [comment]
fixed in 

https://github.com/Pivosgroup/buildroot-linux/commit/951088aff2ca5f08b69f82d04b1544760d4a5ec9
https://github.com/Pivosgroup/xbmc/commit/ff91e9204912b416a98d1a6f849776cec28ef451
