### ISSUE TITLE
Underruns on streaming http

### ISSUE THREAD

**Issue by emveepee** [Pivosgroup/buildroot-linux#25]
Using beta3 951088a when I play an atsc stream on live tv I get regular audio cuts out that correlate to the logs as underruns

17:17:54 T:1102255200   DEBUG: CSoftAEStream::GetFrame - Underrun
17:17:57 T:1242121312   DEBUG: CDVDPlayerAudio:: Discontinuity - was:10323739.5
47618, should be:7904000.222222, error:-2419739.325396
17:17:57 T:1395041376  NOTICE: 2012-12-09 17:18:07.674708
17:17:57 T:1242121312   DEBUG: CDVDPlayerAudio:: Discontinuity - was:8106051.22
2222, should be:7904000.222222, error:-202051.000000
17:17:59 T:1242121312   DEBUG: CDVDPlayerAudio:: Discontinuity - was:9912288.22
2222, should be:9844087.698412, error:-68200.523809
17:18:01 T:1242121312   DEBUG: CDVDPlayerAudio:: Discontinuity - was:11964203.6
98412, should be:11946222.805555, error:-17980.892857

**Comment by davilla** [comment]
passthough or downmix ?
same behavior on desktop beta3 ?

**Comment by emveepee** [comment]
Downmix, I can check passthrough later.   Desktop beta3 (Win32) is OK.  Can check OpenElec ION and RPi if you'd like but haven't noticed problems on them.

Martin

**Comment by emveepee** [comment]
I am  closing this since I am no longer seeing underruns  in the logs with the most recent nightlies

Martin
