### ISSUE TITLE
path substitution problem

### ISSUE THREAD

**Issue by yang299kms** [Pivosgroup/buildroot-linux#27]
i have these path subs in my /root/.xbmc/userdata/advancedsettings.xml, same settings i had for a long time, the source.xml path stopped working (12.0-BETA3 Git:20121209-951088a).  i had to comment it out and use a local /root/.xbmc/userdata/sources.xml

```
    <pathsubstitution>
            <substitute>
                    <from>special://masterprofile/Thumbnails/Video/</from>
                    <to>nfs://10.0.1.18/volume1/Media/xbmc/userdata/Thumbnails/Video/</to>
            </substitute>
            <substitute>
                    <from>special://masterprofile/Thumbnails/Music/</from>
                    <to>nfs://10.0.1.18/volume1/Media/xbmc/userdata/Thumbnails/Music/</to>
            </substitute>
            <substitute>
                    <from>special://masterprofile/favourites.xml</from>
                    <to>nfs://10.0.1.18/volume1/Media/xbmc/userdata/favourites.xml</to>
            </substitute>
            <substitute>
                    <from>special://masterprofile/sources.xml</from>
                    <to>nfs://10.0.1.18/volume1/Media/xbmc/userdata/sources.xml</to>
            </substitute>
            <substitute>
                    <from>special://masterprofile/mediasources.xml</from>
                    <to>nfs://10.0.1.18/volume1/Media/xbmc/userdata/mediasources.xml</to>
            </substitute>
    </pathsubstitution>
```

**Comment by davilla** [comment]
"path substitu" is not enough to understand

**Comment by yang299kms** [comment]
i hit enter at the wrong time,  should i make another?

**Comment by davilla** [comment]
does XBMC mainline also does this ?

**Comment by emveepee** [comment]
path substitution was broken with the beta3 release and fixed on Dec 8 https://github.com/xbmc/xbmc/commit/334d12d177a43f7e6b6e78bf596ef72ac4ada033

Martin

**Comment by yang299kms** [comment]
i did another cleanup today with hash XBMC (12.0-BETA3 Git:20121213-e6f0748) and the path subs don't does not work properly. i flashed back to an older beta2 image and everything works. i tested the same advancedsettings.xml on my iPad with rc1 and it works fine.  my sources.xml is not read in the BETA3 build

**Comment by yang299kms** [comment]
I'll test with another build tomorrow after I patch with that fix emv points out

**Comment by yang299kms** [comment]
confirmed fixed w/ xbmc mainline

**Comment by davilla** [comment]
ok, we will pull that in when we bump to rc1 or rc2.

**Comment by yang299kms** [comment]
gonna close this since its fixed in rc1.
