### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by yang299kms** [Pivosgroup/buildroot-linux#30]
Subtitles no longer display unless I bring up the info screen "i" on a keyboard. If I bring up the OSD using the enter key subtitles are no longer displayed, but info OSD will bring back the subtitles.

When the subtitles are on I see them semi transparent, this could be a beta3 issue since my rc1 iPad version shows subtitles and isn't transparent.

**Comment by davilla** [comment]
try this commit
https://github.com/xbmc/xbmc/commit/cd1251107a725cfed96746dad2313e588cfc6252

**Comment by yang299kms** [comment]
i tried that commit and 2 others related to subtitles none worked. 
https://github.com/xbmc/xbmc/commit/70d4e49c56c8b8cdf4f7f5add0e569f472f3464d
https://github.com/xbmc/xbmc/commit/7452460c714f105470f837b0aa1449684bb4eaeb

**Comment by yang299kms** [comment]
i sync'ed my cloned pivos xbmc to xbmc master and subtitles still no go.

**Comment by davilla** [comment]
what type of subtiles are you testing ?

**Comment by yang299kms** [comment]
its one of these videos w/ loads of subs an its vobsub, all the others subs that are S_TEXT/UTF8 seems to work fine w/ RC1.

General
Complete name                            : /Volumes/Media/Movies/Premium.Rush.2012.720p.BluRay.DTS.x264-PublicHD/premium.rush.2012.720p.bluray.dts.x264-publichd.nfo
File size                                : 1.23 KiB

General
Complete name                            : /Volumes/Media/Movies/Premium.Rush.2012.720p.BluRay.DTS.x264-PublicHD/Downloaded from PublicHD.EU.txt
File size                                : 92.0 Bytes

General
Unique ID                                : 175185100305572279632288447507877365034 (0x83CB6C4CEEBEDFBC892454D4EEA0852A)
Complete name                            : /Volumes/Media/Movies/Premium.Rush.2012.720p.BluRay.DTS.x264-PublicHD/premium.rush.2012.720p.bluray.dts.x264-publichd.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 4.32 GiB
Duration                                 : 1h 30mn
Overall bit rate                         : 6 796 Kbps
Encoded date                             : UTC 2012-11-28 22:47:50
Writing application                      : mkvmerge v5.8.0 ('No Sleep / Pillow') built on Sep  2 2012 15:37:04
Writing library                          : libebml v1.2.3 + libmatroska v1.3.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1h 30mn
Bit rate                                 : 5 373 Kbps
Width                                    : 1 280 pixels
Height                                   : 532 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.329
Stream size                              : 3.27 GiB (76%)
Writing library                          : x264 core 125 r2200 999b753
Encoding settings                        : cabac=1 / ref=6 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=5373 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 1h 30mn
Bit rate mode                            : Constant
Bit rate                                 : 1 509 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 982 MiB (22%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Arabic
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 5
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Bulgarian
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 6
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Croatian
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 7
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Czech
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 8
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Estonian
Default                                  : No
Forced                                   : No

Text #7
ID                                       : 9
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Hindi
Default                                  : No
Forced                                   : No

Text #8
ID                                       : 10
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Icelandic
Default                                  : No
Forced                                   : No

Text #9
ID                                       : 11
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Polish
Default                                  : No
Forced                                   : No

Text #10
ID                                       : 12
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Portuguese
Default                                  : No
Forced                                   : No

Text #11
ID                                       : 13
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Romanian
Default                                  : No
Forced                                   : No

Text #12
ID                                       : 14
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Slovak
Default                                  : No
Forced                                   : No

Text #13
ID                                       : 15
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Slovenian
Default                                  : No
Forced                                   : No

Text #14
ID                                       : 16
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Turkish
Default                                  : No
Forced                                   : No

Text #15
ID                                       : 17
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Ukrainian
Default                                  : No
Forced                                   : No

Text #16
ID                                       : 18
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Hungarian
Default                                  : No
Forced                                   : No

Text #17
ID                                       : 19
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Lithuanian
Default                                  : No
Forced                                   : No

Text #18
ID                                       : 20
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : The same subtitle format used on DVDs
Language                                 : Russian
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:00:00:00.000
00:05:43.301                             : en:00:05:43.301
00:10:33.675                             : en:00:10:33.675
00:19:39.845                             : en:00:19:39.845
00:22:41.402                             : en:00:22:41.402
00:28:54.107                             : en:00:28:54.107
00:33:01.563                             : en:00:33:01.563
00:37:37.172                             : en:00:37:37.172
00:44:25.413                             : en:00:44:25.413
00:50:52.758                             : en:00:50:52.758
00:55:17.773                             : en:00:55:17.773
00:58:40.600                             : en:00:58:40.600
01:02:10.936                             : en:01:02:10.936
01:09:15.234                             : en:01:09:15.234
01:15:52.757                             : en:01:15:52.757
01:22:29.862                             : en:01:22:29.862

**Comment by ghost** [comment]
I have this problem too, subtitles only display with OSD. my subtitles are all vobsub. This is for M1 - 121512

**Comment by theuni** [comment]
b23b4c0997734557e66e18c597b5da28f3038617 (in xbmc repo) is likely to blame here. If so, we'll need to be more clever about how this is done.

**Comment by sagacity** [comment]
FYI, external .srt subs also don't work anymore.

**Comment by theuni** [comment]
Should be fixed with https://github.com/Pivosgroup/xbmc/commit/9df0520208b11442755a3db717364c4ce5bfc8e1
