### ISSUE TITLE
WMV playback not working

### ISSUE THREAD

**Issue by gammaray-co** [Pivosgroup/buildroot-linux#46]
Windows media video playback has been broken since the original release in August 2012.

You can use this file to verify:

http://download.nvidia.com/video/purevideo/PureVideo-USA-720p.wmv

**Comment by davilla** [comment]
WMV playback works on Pivos/Linux/M3

**Comment by gammaray-co** [comment]
Not for me. Pretty much none of the files or streams have video. Am I doing something wrong? Do you need logs or anything else from me?

**Comment by davilla** [comment]
Some forms of WMV will never play, nothing we can do about that. HW decoder issue. PureVideo-USA-720p.wmv plays on the current buildroot-linux for Pivos/Linux/M3.

**Comment by gammaray-co** [comment]
I must be either doing something wrong, or i have a defective box, cause i
can't get that video to play on xios/linux/M3. I have reset it to factory
defaults, wiped cache, reapplied 012913 update, reset it to factory again,
wiped cache again, and i can't get it to play that video. Only audio is
playing, no video, and even the audio is choppy. I have tried both from USB
and SMB. I do not have any plugins loaded, and i have not changed any
settings.

What am I doing wrong? and what other info do you need from me to show you
that this video is not working?

Thanks.

**Comment by gammaray-co** [comment]
Just tested the latest nightly, and it looks like it is fixed. 

Thanks guys.
