### ISSUE TITLE
can NOT complie for M1

### ISSUE THREAD

**Issue by ljwzsjs** [Pivosgroup/buildroot-linux#61]
CC [M]  drivers/amlogic/mali/common/mali_kernel_core.o
arm-none-linux-gnueabi-gcc: ": No such file or directory
<command-line>:0: warning: missing terminating " character
In file included from drivers/amlogic/mali/common/mali_uk_types.h:24,
                 from drivers/amlogic/mali/common/mali_kernel_subsystem.h:19,
                 from drivers/amlogic/mali/common/mali_kernel_core.c:11:
/media/71572db3-d2f7-4941-8742-6a446c1ee44c/buildroot-linux/output/build/linux-1405682aa1b1bdc6b923f21b7a51c9a45734c340/drivers/amlogic/mali/regs/mali_200_regs.h:102: error: #error "No supported mali core defined"
/media/71572db3-d2f7-4941-8742-6a446c1ee44c/buildroot-linux/output/build/linux-1405682aa1b1bdc6b923f21b7a51c9a45734c340/drivers/amlogic/mali/regs/mali_200_regs.h:124: error: #error "No supported mali core defined"
/media/71572db3-d2f7-4941-8742-6a446c1ee44c/buildroot-linux/output/build/linux-1405682aa1b1bdc6b923f21b7a51c9a45734c340/drivers/amlogic/mali/regs/mali_200_regs.h:144: error: #error "No supported mali core defined"
/media/71572db3-d2f7-4941-8742-6a446c1ee44c/buildroot-linux/output/build/linux-1405682aa1b1bdc6b923f21b7a51c9a45734c340/drivers/amlogic/mali/regs/mali_200_regs.h:166: error: #error "No supported mali core defined"
In file included from drivers/amlogic/mali/common/mali_kernel_subsystem.h:19,
                 from drivers/amlogic/mali/common/mali_kernel_core.c:11:
drivers/amlogic/mali/common/mali_uk_types.h:568: error: 'MALI200_NUM_REGS_FRAME' undeclared here (not in a function)
drivers/amlogic/mali/common/mali_kernel_core.c: In function 'mali_kernel_constructor':
drivers/amlogic/mali/common/mali_kernel_core.c:167: error: missing terminating " character
drivers/amlogic/mali/common/mali_kernel_core.c:167: error: expected expression before ')' token
drivers/amlogic/mali/common/mali_kernel_core.c:172: error: missing terminating " character
drivers/amlogic/mali/common/mali_kernel_core.c:172: error: expected expression before ')' token
make[4]: **\* [drivers/amlogic/mali/common/mali_kernel_core.o]

---

error for "Build for M1".
"Build for M3" is OK.

**Comment by davilla** [comment]
Please describe the missing parts of your build sequence. Build env too.

**Comment by ljwzsjs** [comment]
My OS is ubuntu 12.04 LTS in virtual box.
I think i know the reason now.
My OS language is chinese.

after change language, it is OK.

---

$ export LC_ALL=en_US.utf8
$ export LANG=en_US

---
