### ISSUE TITLE
Powering off

### ISSUE THREAD

**Issue by tvro** [Pivosgroup/buildroot-linux#65]
After doing a update to the 05/10/13 Linux firmware when I turn off xbmc says shutting down now ready to turn off and will not turn off does this on 2 M3 pivos's both after clean install M1 seems ok. Only way to shut down is remove power

**Comment by aasoror** [comment]
Thats expected, M3 doesn't totally shutdown, you can either go to standby or put the box in a ready to shutdown state where you need to unplug it.
The "ready to shutdown" was meant for those who don't even want to put the unit to standby and would rather completely turn it off, this allows them for graceful shutdown (vs. just unplugging the unit while its running).

**Comment by tvro** [comment]
Thanks for the reply I had a M1 version and it shuts down so when I was updating these for my sister they didn't shut off so will tell her to put in standby
