### ISSUE TITLE
Subtitle always show - even if turned off in guisettings.xml

### ISSUE THREAD

**Issue by docthomas** [Pivosgroup/buildroot-linux#8]
Video files that have Subtitles in the container will always play even if I have turned off subtitles in guisettings.xml.  

Ideally I would like to have an option in the video play that allows you to turn on or off during playback.

**Comment by davilla** [comment]
OSD -> video -> subtitles on/off. Note that if the subs are hard coded, we have no control over them.

**Comment by docthomas** [comment]
Ok that works so I guess the issue is:
No way to set a global option of subtitles on/off - unless you use the OSD-Video-Subtitles.  
But this is a problem from the XBMC source and not just the pivos build.  

Thanks

**Comment by amet** [comment]
yes there is, if you go to the same menu last option says "save for all movies", hit that and all files will play without subs by default.

indeed, its XBMC global setting/issue
